// i18n-ignore: Developer-only catalog; user authorized fixed Chinese copy.
export const categories = [
  { id: "actions", label: "操作与反馈" },
  { id: "forms", label: "表单与配置" },
  { id: "layout", label: "导航与布局" },
  { id: "overlays", label: "弹层与菜单" },
  { id: "icons", label: "图标" },
] as const;
export const componentCatalog = [
  {
    name: "Select",
    category: "forms",
    purpose: "三项及以上优先下拉；默认向下展开，支持弹层内快速搜索。",
    forms: "selected / disabled / searchable / 键盘与焦点",
  },
  {
    name: "Switch",
    category: "forms",
    purpose: "明确开启或关闭一项配置。",
    forms: "checked · unchecked / disabled",
  },
  {
    name: "FormField",
    category: "forms",
    purpose: "统一 TextInput、标签、说明与错误关联。",
    forms: "text · password / disabled · invalid / description",
  },
  {
    name: "ChoiceGroup",
    category: "forms",
    purpose: "在两个明确值之间直接切换，选中项使用轻量胶囊底色。",
    forms: "selected · unselected / disabled / radio keyboard",
  },
  {
    name: "SettingsGroup",
    category: "forms",
    purpose: "组合设置页、分组与配置行。",
    forms:
      "SettingsPage · SettingsGroup · SettingRow / label · description · control",
  },
  {
    name: "Button",
    category: "actions",
    purpose: "主操作、轻量操作和导航选择。",
    forms:
      "default · secondary · ghost · navigation / default · icon / disabled · pressed",
  },
  {
    name: "IconButton",
    category: "actions",
    purpose: "带可访问名称、提示和角标的图标操作。",
    forms: "tooltip / 0 · 999+ · 状态角标 / disabled",
  },
  {
    name: "WorkspaceTabs",
    category: "layout",
    purpose: "切换、关闭工作页签，使用方向键、Home 和 End 导航。",
    forms: "selected · unselected / 可关闭 / 空状态",
  },
  {
    name: "ResizableSplit",
    category: "layout",
    purpose: "拖动分隔线或使用方向键调整面板。",
    forms: "horizontal · vertical / start · end / visible · hidden",
  },
  {
    name: "NavigationOverlay",
    category: "overlays",
    purpose: "临时展开导航，关闭后焦点返回触发按钮。",
    forms: "closed · open / Esc 关闭 / 焦点约束",
  },
  {
    name: "SettingsModal",
    category: "overlays",
    purpose: "带独立导航与内容区域的设置弹层。",
    forms: "closed · open / 页内导航 / Esc 关闭",
  },
  {
    name: "Icon Layer",
    category: "icons",
    purpose: "自动收录项目 Icon Layer 的公开图标，仅作预览。",
    forms: "16 · 18 · 20 · 24 px / currentColor / 新增图标自动出现",
  },
] as const;
export type ComponentName = (typeof componentCatalog)[number]["name"];
export const menuEntry = {
  name: "HoverMenu",
  category: "overlays",
  purpose: "悬停、点击或使用键盘打开工具选项。",
  forms: "closed · open / hover · click · keyboard / Esc 关闭",
};
export const copy = {
  title: "基础组件看板",
  intro: "查看组件形态与状态，直接体验交互。",
  search: "搜索组件",
  index: "组件索引",
  searchHint: "名称、用途、形态…",
  all: "全部",
  empty: "没有匹配的组件",
  emptyHint: "试试其他名称、用途或形态，或清空搜索。",
  clear: "清空搜索",
  reset: "重置",
  resetLabel: (name: string) => `重置 ${name}`,
  count: (visible: number, total: number) => `${visible} / ${total} 项`,
};

export const demoLabels = {
  select: "默认行为",
  optionC: "选项 C",
  searchableSelect: "可搜索选择",
  searchOptions: "搜索选项",
  noOptions: "没有匹配的选项",
  optionA: "选项 A",
  optionB: "选项 B",
  switch: "开启功能",
  field: "配置内容",
  fieldDescription: "标签和说明自动关联到输入框。",
  fieldError: "示例错误：内容不符合要求。",
  mode: "显示方式",
  settingsPageTitle: "配置组件",
  settingsDescription: "只使用本地示例状态。",
  settingsGroup: "通用设置",
  settingsRow: "默认选项",
  settingsRowDescription: "说明与控件共享同一配置行。",
  primary: "主操作",
  ghost: "轻量操作",
  navigation: "导航选择",
  disabled: "禁用",
  pressed: "选中",
  idle: "未选中",
  add: "添加演示项目",
  icon: "图标尺寸",
  buttonFeedback: "按钮反馈",
  buttonCount: (count: number) => `已点击 ${count} 次`,
  iconFeedback: (count: number) => `添加了 ${count} 个演示项目`,
  zero: "计数为 0",
  overflow: "计数超过 999",
  attention: "有新状态",
  inactive: "禁用图标操作",
  files: "文件",
  preview: "预览",
  settings: "设置",
  closeTab: (title: string) => `关闭 ${title}`,
  tabBody: "当前页签：",
  tabEmpty: "页签已全部关闭，重置可恢复。",
  horizontal: "横向 / start",
  vertical: "纵向 / end",
  horizontalLabel: "调整横向面板",
  verticalLabel: "调整纵向面板",
  mainPanel: "主要内容",
  auxiliaryPanel: "辅助面板",
  hide: "隐藏辅助面板",
  show: "显示辅助面板",
  panelSize: (size: number) => `辅助面板 ${Math.round(size)} px`,
  openNavigation: "打开导航抽屉",
  closeNavigation: "关闭导航抽屉",
  navigationTitle: "导航抽屉演示",
  openSettings: "打开设置弹层",
  closeSettings: "关闭设置弹层",
  settingsTitle: "设置弹层演示",
  overview: "概览",
  appearance: "外观",
  about: "关于",
  overlayHint: "这是本地演示，选择选项不会影响真实应用。",
  choice: (value: string) => `当前选项：${value}`,
};
