// i18n-ignore: Developer-only catalog; user authorized fixed Chinese copy.
export const categories = [
  { id: "actions", label: "操作与反馈" },
  { id: "layout", label: "导航与布局" },
  { id: "overlays", label: "弹层与菜单" },
  { id: "icons", label: "图标" },
] as const;
export const componentCatalog = [
  {
    name: "Button",
    category: "actions",
    purpose: "主操作、轻量操作和导航选择。",
    forms: "default · ghost · navigation / default · icon / disabled · pressed",
  },
  {
    name: "IconButton",
    category: "actions",
    purpose: "带可访问名称、提示和角标的图标操作。",
    forms: "tooltip / 0 · 999+ · 状态角标 / disabled",
  },
  {
    name: "WorkspaceTabs",
    category: "layout",
    purpose: "切换、关闭工作页签，使用方向键、Home 和 End 导航。",
    forms: "selected · unselected / 可关闭 / 空状态",
  },
  {
    name: "ResizableSplit",
    category: "layout",
    purpose: "拖动分隔线或使用方向键调整面板。",
    forms: "horizontal · vertical / start · end / visible · hidden",
  },
  {
    name: "NavigationOverlay",
    category: "overlays",
    purpose: "临时展开导航，关闭后焦点返回触发按钮。",
    forms: "closed · open / Esc 关闭 / 焦点约束",
  },
  {
    name: "SettingsModal",
    category: "overlays",
    purpose: "带独立导航与内容区域的设置弹层。",
    forms: "closed · open / 页内导航 / Esc 关闭",
  },
  {
    name: "Icon Layer",
    category: "icons",
    purpose: "应用实际使用的语义图标，继承当前主题颜色。",
    forms: "16 · 18 · 20 · 24 px / WebsiteIcon github · generic",
  },
] as const;
export type ComponentName = (typeof componentCatalog)[number]["name"];
export const menuEntry = {
  name: "HoverMenu",
  category: "overlays",
  purpose: "悬停、点击或使用键盘打开工具选项。",
  forms: "closed · open / hover · click · keyboard / Esc 关闭",
};
export const copy = {
  title: "基础组件看板",
  intro:
    "浏览已有组件的形态与状态，直接操作体验。演示状态独立，重置后可重新开始。",
  search: "搜索组件",
  searchHint: "名称、用途、形态…",
  all: "全部",
  empty: "没有匹配的组件",
  emptyHint: "试试其他名称、用途或形态，或清空搜索。",
  clear: "清空搜索",
  reset: "重置",
  resetLabel: (name: string) => `重置 ${name}`,
  count: (visible: number, total: number) => `${visible} / ${total} 项`,
};

export const demoLabels = {
  primary: "主操作",
  ghost: "轻量操作",
  navigation: "导航选择",
  disabled: "禁用",
  pressed: "选中",
  idle: "未选中",
  add: "添加演示项目",
  icon: "图标尺寸",
  buttonFeedback: "按钮反馈",
  buttonCount: (count: number) => `已点击 ${count} 次`,
  iconFeedback: (count: number) => `添加了 ${count} 个演示项目`,
  zero: "计数为 0",
  overflow: "计数超过 999",
  attention: "有新状态",
  inactive: "禁用图标操作",
  files: "文件",
  preview: "预览",
  settings: "设置",
  closeTab: (title: string) => `关闭 ${title}`,
  tabBody: "当前页签：",
  tabEmpty: "页签已全部关闭，重置可恢复。",
  horizontal: "横向 / start",
  vertical: "纵向 / end",
  horizontalLabel: "调整横向面板",
  verticalLabel: "调整纵向面板",
  mainPanel: "主要内容",
  auxiliaryPanel: "辅助面板",
  hide: "隐藏辅助面板",
  show: "显示辅助面板",
  panelSize: (size: number) => `辅助面板 ${Math.round(size)} px`,
  openNavigation: "打开导航抽屉",
  closeNavigation: "关闭导航抽屉",
  navigationTitle: "导航抽屉演示",
  openSettings: "打开设置弹层",
  closeSettings: "关闭设置弹层",
  settingsTitle: "设置弹层演示",
  overview: "概览",
  appearance: "外观",
  about: "关于",
  overlayHint: "这是本地演示，选择选项不会影响真实应用。",
  choice: (value: string) => `当前选项：${value}`,
  iconSize: "图标预览尺寸",
};
